Repository caproto/caproto, pull requests merged in 2018-06, with the labels that each got.

#215 REF: abstract ioctl call in threaded selector
  .travis.yml
  appveyor.yml
  caproto/__init__.py
  caproto/_log.py
  caproto/_utils.py
  caproto/_windows_compat.py
  caproto/benchmarking/util.py
  caproto/curio/client.py
  caproto/examples/defaultdictserver.py
  caproto/examples/spoof_beamline.py
  caproto/examples/thread_client_simple.py
  caproto/ioc_examples/areadetector_image.py
  caproto/ioc_examples/custom_write.py
  caproto/ioc_examples/type_varieties.py
  caproto/server/common.py
  caproto/sync/client.py
  caproto/sync/repeater.py
  caproto/tests/conftest.py
  caproto/tests/epics_test_utils.py
  caproto/tests/example_runner.py
  caproto/tests/test_bench.py
  caproto/tests/test_cli_scripts.py
  caproto/tests/test_create_many_channels.py
  caproto/tests/test_examples.py
  caproto/tests/test_pyepics_compat.py
  caproto/tests/test_server.py
  caproto/tests/test_threading_client.py
  caproto/threading/client.py
  caproto/threading/pyepics_compat.py
  caproto/trio/client.py
  scripts/caproto-get
  scripts/caproto-monitor
  scripts/caproto-put
  scripts/caproto-repeater
  scripts/defaultdictserver
  setup.py
Labels: high-priority, work-in-progress

#198 API: Be more intentional with public API.
  caproto/__init__.py
  caproto/_backend.py
  caproto/_broadcaster.py
  caproto/_circuit.py
  caproto/_commands.py
  caproto/_data.py
  caproto/_dbr.py
  caproto/_log.py
  caproto/_status.py
  caproto/_utils.py
  caproto/server/common.py
  caproto/tests/test_cli_scripts.py
  caproto/tests/test_dbr_types.py
  caproto/tests/test_serialization.py
  caproto/tests/test_utils.py
  doc/source/api.rst
Labels: high-priority

#252 MNT: update header generation
  caproto/_headers.py
  caproto/headers.tpl
  caproto/tests/test_serialization.py
Labels: ready-for-review

#287 ENH: add full support for the sync filter
  caproto/_data.py
  caproto/_utils.py
  caproto/ioc_examples/states.py
  caproto/server/common.py
  caproto/server/records.py
  caproto/server/server.py
  caproto/tests/conftest.py
  caproto/tests/test_channel_filters.py
  caproto/tests/test_threading_client.py
Labels: high-priority
